### ISSUE TITLE
Plugin path not found

### ISSUE THREAD

**Issue by benzntech** [Steveorevo/hestiacp-nodeapp#1]
There is no such folder as below in latest hestiacp
cd /usr/local/hestia/plugins

**Comment by Steveorevo** [comment]
The plugins folder is created by hestiacp-pluginable. See requirements in the README.md.

**Comment by benzntech** [comment]
There is no such folder as Plugins itself
cd /usr/local/hestia/plugins

![image](https://user-images.githubusercontent.com/4044180/232445638-3a59c99e-5752-4071-90a2-3b997ead90aa.png)

![image](https://user-images.githubusercontent.com/4044180/232445913-faa25154-7164-46ec-975f-c901320efa2a.png)

**Comment by Steveorevo** [comment]
The README.md file says:

“ (via [hestiacp-pluginable](https://github.com/steveorevo/hestiacp-pluginable))”

if you do not have a plugins folder then you must not have HestiaCP-Pluginable installed or there is a problem with HestiaCP-Pluginable. 

Please create an issue on HestiaCP-Pluginable, not here.
