### ISSUE TITLE
Already-existing sub-user .bashrc not modified

### ISSUE THREAD

**Issue by ralphstodomingo** [Steveorevo/hestiacp-nodeapp#5]
First off, thanks for all this, managed to use this on my instance and got a node project hosted, works mostly as intended.

This is probably not a hcpp-nodeapp issue, but during installation, I found that the .bashrc modifications don't copy over to the subusers, only takes effect for the root user. I had to manually copy over the modifications the installation makes before I got it working. Anything I'm doing wrong with the setup? Concerned it will affect the other subusers I'll add to my instance.

**Comment by Steveorevo** [comment]
Thank you for your inquiry. On line 61 on the install we do see:
```
cat <<EOT >> /etc/bash.bashrc
# begin hcpp-nodeapp
export NVM_DIR="/opt/nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="/opt/nvm:\$PATH"
# end hcpp-nodeapp
EOT
```

This global .bashrc setting should have an effect on all users. If not, a reboot maybe necessary.

**Comment by ralphstodomingo** [comment]
Tried a reboot then, didn't take effect as expected. But maybe it was something else. Thanks!
